# Generated by Django 5.2.6 on 2025-09-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/default.png', height_field=1, upload_to='products/', width_field=1),
        ),
    ]
