# Generated by Django 5.2.6 on 2025-09-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
