# Generated by Django 5.2.6 on 2025-09-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_component_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='image',
            new_name='image_url',
        ),
    ]
